# fly.toml file generated for cryptlinks on 2023-03-27T03:02:29+02:00

app = "cryptlinks"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "cdg"

[build]
  image = "fhilgers/cryptlinks:latest"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
